### ISSUE TITLE
Unspecified "prune_graph" package?

### ISSUE THREAD

**Issue by SereneWalden** [gsartoretti/distributedRL_MAPF#1]
\od_mstar3\od_mstar.py, 
Line 1235: import prune_graph

May I ask what is this "prune_graph" package that is imported here? Can't find it either in this repository or PyPi resources.

BTW Impressive paper, kudos~

**Comment by gsartoretti** [comment]
Hi Serene,

Thanks a lot for your comment and compliment, I appreciate it a lot!

If you get this issue, it means you are not importing the right od_mstar package. That is, you should never import od_mstar.py. You should follow the repo's README that explains how to compile the C++ version of od_mstar, and then import mstar_cpp from the od_mstar3 folder.

Now, if you really want to use od_mstar.py (and in particular that one function in it that triggers this import of prune_graph), I will be quickly adding the prune_graph.py file to the od_mstar3, and you can then git pull and everything should work. But I would not recommend doing so, and rather use the C++ implementation of the code (way faster), as explained in the repo's README.

Let me know if this solves the issue (in which case feel free to close the issue), and if you need any further help.
Best,

Guillaume
