### ISSUE TITLE
"ImportError: cannot import name 'cpp_mstar'" after python setup.py build_ext --inplace

### ISSUE THREAD

**Issue by cloud-tifa** [gsartoretti/distributedRL_MAPF#5]
Dear Dr. Sartoretti:

I am a student from ECNU, and I'm really interested in your work: multi-agent path finding. But I encountered some problem about the setup.
After running the command  python3 setup.py build_ext --inplace, I got the error saying "ImportError: cannot import name 'cpp_mstar'". Then I checked the od_mstar3 folder and found that indeed had no cpp_mstar.py.
I am confused and trying to look for your suggestions.
Would you know how to solve this problem?

I am looking forward to your response.

Thanks & regards
![image](https://user-images.githubusercontent.com/15826699/70436957-6f83a780-1ac5-11ea-9632-c93b0cc2e961.png)
![image](https://user-images.githubusercontent.com/15826699/70436996-8629fe80-1ac5-11ea-8c98-86623e1028aa.png)

**Comment by sayan1999** [comment]
How did you resolve it?

**Comment by Strawberry47** [comment]
Did you solve this problem?

**Comment by Mealoore** [comment]
you can use "from od_mstart3 import cpp_mstar"

**Comment by wzwb** [comment]
> you can use "from od_mstart3 import cpp_mstar"

Thank you for your help!

**Comment by meo0306** [comment]
did you solve the problem?
